require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ChargeTypesController do

  # This should return the minimal set of attributes required to create a valid
  # ChargeType. As you add validations to ChargeType, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ChargeTypesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all charge_types as @charge_types" do
      charge_type = ChargeType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:charge_types).should eq([charge_type])
    end
  end

  describe "GET show" do
    it "assigns the requested charge_type as @charge_type" do
      charge_type = ChargeType.create! valid_attributes
      get :show, {:id => charge_type.to_param}, valid_session
      assigns(:charge_type).should eq(charge_type)
    end
  end

  describe "GET new" do
    it "assigns a new charge_type as @charge_type" do
      get :new, {}, valid_session
      assigns(:charge_type).should be_a_new(ChargeType)
    end
  end

  describe "GET edit" do
    it "assigns the requested charge_type as @charge_type" do
      charge_type = ChargeType.create! valid_attributes
      get :edit, {:id => charge_type.to_param}, valid_session
      assigns(:charge_type).should eq(charge_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ChargeType" do
        expect {
          post :create, {:charge_type => valid_attributes}, valid_session
        }.to change(ChargeType, :count).by(1)
      end

      it "assigns a newly created charge_type as @charge_type" do
        post :create, {:charge_type => valid_attributes}, valid_session
        assigns(:charge_type).should be_a(ChargeType)
        assigns(:charge_type).should be_persisted
      end

      it "redirects to the created charge_type" do
        post :create, {:charge_type => valid_attributes}, valid_session
        response.should redirect_to(ChargeType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved charge_type as @charge_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeType.any_instance.stub(:save).and_return(false)
        post :create, {:charge_type => {}}, valid_session
        assigns(:charge_type).should be_a_new(ChargeType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeType.any_instance.stub(:save).and_return(false)
        post :create, {:charge_type => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested charge_type" do
        charge_type = ChargeType.create! valid_attributes
        # Assuming there are no other charge_types in the database, this
        # specifies that the ChargeType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ChargeType.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => charge_type.to_param, :charge_type => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested charge_type as @charge_type" do
        charge_type = ChargeType.create! valid_attributes
        put :update, {:id => charge_type.to_param, :charge_type => valid_attributes}, valid_session
        assigns(:charge_type).should eq(charge_type)
      end

      it "redirects to the charge_type" do
        charge_type = ChargeType.create! valid_attributes
        put :update, {:id => charge_type.to_param, :charge_type => valid_attributes}, valid_session
        response.should redirect_to(charge_type)
      end
    end

    describe "with invalid params" do
      it "assigns the charge_type as @charge_type" do
        charge_type = ChargeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeType.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge_type.to_param, :charge_type => {}}, valid_session
        assigns(:charge_type).should eq(charge_type)
      end

      it "re-renders the 'edit' template" do
        charge_type = ChargeType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ChargeType.any_instance.stub(:save).and_return(false)
        put :update, {:id => charge_type.to_param, :charge_type => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested charge_type" do
      charge_type = ChargeType.create! valid_attributes
      expect {
        delete :destroy, {:id => charge_type.to_param}, valid_session
      }.to change(ChargeType, :count).by(-1)
    end

    it "redirects to the charge_types list" do
      charge_type = ChargeType.create! valid_attributes
      delete :destroy, {:id => charge_type.to_param}, valid_session
      response.should redirect_to(charge_types_url)
    end
  end

end
