require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PrayerFollowupsController do

  # This should return the minimal set of attributes required to create a valid
  # PrayerFollowup. As you add validations to PrayerFollowup, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PrayerFollowupsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all prayer_followups as @prayer_followups" do
      prayer_followup = PrayerFollowup.create! valid_attributes
      get :index, {}, valid_session
      assigns(:prayer_followups).should eq([prayer_followup])
    end
  end

  describe "GET show" do
    it "assigns the requested prayer_followup as @prayer_followup" do
      prayer_followup = PrayerFollowup.create! valid_attributes
      get :show, {:id => prayer_followup.to_param}, valid_session
      assigns(:prayer_followup).should eq(prayer_followup)
    end
  end

  describe "GET new" do
    it "assigns a new prayer_followup as @prayer_followup" do
      get :new, {}, valid_session
      assigns(:prayer_followup).should be_a_new(PrayerFollowup)
    end
  end

  describe "GET edit" do
    it "assigns the requested prayer_followup as @prayer_followup" do
      prayer_followup = PrayerFollowup.create! valid_attributes
      get :edit, {:id => prayer_followup.to_param}, valid_session
      assigns(:prayer_followup).should eq(prayer_followup)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new PrayerFollowup" do
        expect {
          post :create, {:prayer_followup => valid_attributes}, valid_session
        }.to change(PrayerFollowup, :count).by(1)
      end

      it "assigns a newly created prayer_followup as @prayer_followup" do
        post :create, {:prayer_followup => valid_attributes}, valid_session
        assigns(:prayer_followup).should be_a(PrayerFollowup)
        assigns(:prayer_followup).should be_persisted
      end

      it "redirects to the created prayer_followup" do
        post :create, {:prayer_followup => valid_attributes}, valid_session
        response.should redirect_to(PrayerFollowup.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved prayer_followup as @prayer_followup" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrayerFollowup.any_instance.stub(:save).and_return(false)
        post :create, {:prayer_followup => {}}, valid_session
        assigns(:prayer_followup).should be_a_new(PrayerFollowup)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        PrayerFollowup.any_instance.stub(:save).and_return(false)
        post :create, {:prayer_followup => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested prayer_followup" do
        prayer_followup = PrayerFollowup.create! valid_attributes
        # Assuming there are no other prayer_followups in the database, this
        # specifies that the PrayerFollowup created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        PrayerFollowup.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => prayer_followup.to_param, :prayer_followup => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested prayer_followup as @prayer_followup" do
        prayer_followup = PrayerFollowup.create! valid_attributes
        put :update, {:id => prayer_followup.to_param, :prayer_followup => valid_attributes}, valid_session
        assigns(:prayer_followup).should eq(prayer_followup)
      end

      it "redirects to the prayer_followup" do
        prayer_followup = PrayerFollowup.create! valid_attributes
        put :update, {:id => prayer_followup.to_param, :prayer_followup => valid_attributes}, valid_session
        response.should redirect_to(prayer_followup)
      end
    end

    describe "with invalid params" do
      it "assigns the prayer_followup as @prayer_followup" do
        prayer_followup = PrayerFollowup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrayerFollowup.any_instance.stub(:save).and_return(false)
        put :update, {:id => prayer_followup.to_param, :prayer_followup => {}}, valid_session
        assigns(:prayer_followup).should eq(prayer_followup)
      end

      it "re-renders the 'edit' template" do
        prayer_followup = PrayerFollowup.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        PrayerFollowup.any_instance.stub(:save).and_return(false)
        put :update, {:id => prayer_followup.to_param, :prayer_followup => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested prayer_followup" do
      prayer_followup = PrayerFollowup.create! valid_attributes
      expect {
        delete :destroy, {:id => prayer_followup.to_param}, valid_session
      }.to change(PrayerFollowup, :count).by(-1)
    end

    it "redirects to the prayer_followups list" do
      prayer_followup = PrayerFollowup.create! valid_attributes
      delete :destroy, {:id => prayer_followup.to_param}, valid_session
      response.should redirect_to(prayer_followups_url)
    end
  end

end
